### ISSUE TITLE
图片无法显示

### ISSUE THREAD

**Issue by Perfeee** [familyld/Machine_Learning#2]
你好，有很多的图床已经失效了。。。

**Comment by familyld** [comment]
是的，之前因为github的latex支持问题换成了图片。我会尽快修复。

**Comment by familyld** [comment]
请安装[GitHub with MathJax](https://chrome.google.com/webstore/detail/github-with-mathjax/ioemnmodlmafdkllaclgeombjnmnbima)插件，谢谢你的关注。
